// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFEqoAUMJNpTGw2edo787MNcxZLT-3n-Y',
    appId: '1:161774930666:web:637cf8d8486a7a3b5ba593',
    messagingSenderId: '161774930666',
    projectId: 'elibrary-8b25d',
    authDomain: 'elibrary-8b25d.firebaseapp.com',
    storageBucket: 'elibrary-8b25d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5po2mES1Way5yk9GlnuD_J0j9vLQm5o',
    appId: '1:161774930666:android:f22dd63cbcd5f86a5ba593',
    messagingSenderId: '161774930666',
    projectId: 'elibrary-8b25d',
    storageBucket: 'elibrary-8b25d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthf4ym9thquyB8JgYrxS7qk_7hGqF4AQ',
    appId: '1:161774930666:ios:986d9def2cb0958e5ba593',
    messagingSenderId: '161774930666',
    projectId: 'elibrary-8b25d',
    storageBucket: 'elibrary-8b25d.appspot.com',
    iosClientId: '161774930666-b1h5ddjd868i9e7j70s3qknnb4vlhedd.apps.googleusercontent.com',
    iosBundleId: 'com.example.elib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCthf4ym9thquyB8JgYrxS7qk_7hGqF4AQ',
    appId: '1:161774930666:ios:986d9def2cb0958e5ba593',
    messagingSenderId: '161774930666',
    projectId: 'elibrary-8b25d',
    storageBucket: 'elibrary-8b25d.appspot.com',
    iosClientId: '161774930666-b1h5ddjd868i9e7j70s3qknnb4vlhedd.apps.googleusercontent.com',
    iosBundleId: 'com.example.elib',
  );
}
